"""pokemon update

Revision ID: 84417dec1d41
Revises: 1f748fc3b2e8
Create Date: 2023-03-05 10:40:46.025145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84417dec1d41'
down_revision = '1f748fc3b2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('abilities', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('sprite', sa.String(length=40), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['pokemon_name'])
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('sprite')
        batch_op.drop_column('abilities')
        batch_op.drop_column('pokemon_name')

    # ### end Alembic commands ###
